import { Lead, Company, CampaignSequence, LeadList } from '../src/types.js';

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead_1',
    firstName: 'Marcus',
    lastName: 'Vance',
    fullName: 'Marcus Vance',
    email: 'm.vance@cloudscale.io',
    personalEmail: 'marcus.vance88@gmail.com',
    phone: '+1 (415) 892-4102',
    title: 'Chief Technology Officer',
    seniority: 'Founder / C-Level',
    department: 'Engineering & IT',
    company: 'CloudScale Systems',
    companyDomain: 'cloudscale.io',
    companyLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=60',
    companySize: '201-500',
    annualRevenue: '$25M - $50M',
    industry: 'Software & SaaS',
    subIndustry: 'Cloud Infrastructure & DevOps',
    location: 'San Francisco, CA, USA',
    city: 'San Francisco',
    state: 'CA',
    country: 'United States',
    linkedin: 'https://linkedin.com/in/marcus-vance-cto',
    twitter: '@marcusv_tech',
    website: 'https://cloudscale.io',
    leadScore: 94,
    emailStatus: 'verified',
    leadStatus: 'qualified',
    source: 'web_scraper',
    tags: ['Cloud Migration', 'Decision Maker', 'High Priority'],
    notes: 'Evaluating multi-cloud orchestrators. Budget approved for Q3.',
    techStack: ['Kubernetes', 'AWS', 'Terraform', 'Datadog', 'PostgreSQL'],
    intentScore: 'High',
    revealed: true,
    createdAt: '2026-08-15T10:30:00Z',
    lastContactedAt: '2026-08-28T14:20:00Z',
  },
  {
    id: 'lead_2',
    firstName: 'Elena',
    lastName: 'Rostova',
    fullName: 'Elena Rostova',
    email: 'elena.rostova@finflow.pay',
    personalEmail: 'elena.rostova@outlook.com',
    phone: '+1 (212) 441-9033',
    title: 'VP of Product & Growth',
    seniority: 'VP / Head of',
    department: 'Product',
    company: 'FinFlow Payments',
    companyDomain: 'finflow.pay',
    companyLogo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=100&auto=format&fit=crop&q=60',
    companySize: '51-200',
    annualRevenue: '$15M - $30M',
    industry: 'FinTech',
    subIndustry: 'Cross-border Payments & Banking',
    location: 'New York, NY, USA',
    city: 'New York',
    state: 'NY',
    country: 'United States',
    linkedin: 'https://linkedin.com/in/elena-rostova-growth',
    twitter: '@elena_finflow',
    website: 'https://finflow.pay',
    leadScore: 89,
    emailStatus: 'verified',
    leadStatus: 'meeting_scheduled',
    source: 'ai_discovery',
    tags: ['High Intent', 'Fast Growth', 'Series B'],
    notes: 'Demo scheduled for Friday 2 PM. Looking to automate enterprise fraud pipelines.',
    techStack: ['Stripe', 'Node.js', 'React', 'Snowflake', 'Segment'],
    intentScore: 'High',
    revealed: true,
    createdAt: '2026-08-18T08:15:00Z',
    lastContactedAt: '2026-08-29T11:00:00Z',
  },
  {
    id: 'lead_3',
    firstName: 'Devon',
    lastName: 'Zhao',
    fullName: 'Devon Zhao',
    email: 'd.zhao@biohealthera.com',
    phone: '+1 (617) 552-8819',
    title: 'Director of Clinical Informatics',
    seniority: 'Director',
    department: 'Healthcare Technology',
    company: 'BioHealth Era',
    companyDomain: 'biohealthera.com',
    companyLogo: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=100&auto=format&fit=crop&q=60',
    companySize: '501-1,000',
    annualRevenue: '$80M - $120M',
    industry: 'Healthcare & Biotech',
    subIndustry: 'Digital Health & Telemedicine',
    location: 'Boston, MA, USA',
    city: 'Boston',
    state: 'MA',
    country: 'United States',
    linkedin: 'https://linkedin.com/in/devon-zhao-health',
    website: 'https://biohealthera.com',
    leadScore: 82,
    emailStatus: 'verified',
    leadStatus: 'contacted',
    source: 'domain_extractor',
    tags: ['Enterprise', 'HIPAA Compliant', 'Boston Hub'],
    notes: 'Responded to cold sequence step 1. Requested security compliance deck.',
    techStack: ['Epic EHR', 'AWS HealthLake', 'FastAPI', 'Postgres'],
    intentScore: 'Medium',
    revealed: false,
    createdAt: '2026-08-20T14:45:00Z',
  },
  {
    id: 'lead_4',
    firstName: 'Sarah',
    lastName: 'Jenkins',
    fullName: 'Sarah Jenkins',
    email: 'sarah.j@nextecom.store',
    phone: '+1 (312) 773-1092',
    title: 'Head of Omnichannel Commerce',
    seniority: 'VP / Head of',
    department: 'E-Commerce & Marketing',
    company: 'NextEcom Direct',
    companyDomain: 'nextecom.store',
    companyLogo: 'https://images.unsplash.com/photo-1556742049-0a67c557688c?w=100&auto=format&fit=crop&q=60',
    companySize: '51-200',
    annualRevenue: '$20M - $40M',
    industry: 'E-Commerce & Retail',
    subIndustry: 'D2C Consumer Goods',
    location: 'Chicago, IL, USA',
    city: 'Chicago',
    state: 'IL',
    country: 'United States',
    linkedin: 'https://linkedin.com/in/sarah-jenkins-ecom',
    twitter: '@sarahj_commerce',
    website: 'https://nextecom.store',
    leadScore: 78,
    emailStatus: 'guessed',
    leadStatus: 'new',
    source: 'web_scraper',
    tags: ['Shopify Plus', 'Direct to Consumer', 'Ad Spender'],
    notes: 'High ad spend on Meta & Google. Potential customer for conversion rate optimization.',
    techStack: ['Shopify Plus', 'Klaviyo', 'Google Ads', 'BigQuery', 'Gorgias'],
    intentScore: 'Medium',
    revealed: false,
    createdAt: '2026-08-22T09:10:00Z',
  },
  {
    id: 'lead_5',
    firstName: 'Alexander',
    lastName: 'Wright',
    fullName: 'Alexander Wright',
    email: 'awright@cybershield.security',
    phone: '+44 20 7946 0912',
    title: 'Chief Information Security Officer (CISO)',
    seniority: 'Founder / C-Level',
    department: 'Information Security',
    company: 'CyberShield Global',
    companyDomain: 'cybershield.security',
    companyLogo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=100&auto=format&fit=crop&q=60',
    companySize: '1,001-5,000',
    annualRevenue: '$150M - $300M',
    industry: 'Cybersecurity',
    subIndustry: 'Threat Intelligence & SOC',
    location: 'London, United Kingdom',
    city: 'London',
    country: 'United Kingdom',
    linkedin: 'https://linkedin.com/in/alexander-wright-ciso',
    website: 'https://cybershield.security',
    leadScore: 96,
    emailStatus: 'verified',
    leadStatus: 'in_negotiation',
    source: 'ai_discovery',
    tags: ['Tier 1 Account', 'SOC2', 'Enterprise Deal'],
    notes: 'Legal review ongoing. Commercial proposal of $120k ARR submitted.',
    techStack: ['Okta', 'CrowdStrike', 'Splunk', 'Azure', 'Palo Alto Networks'],
    intentScore: 'High',
    revealed: true,
    createdAt: '2026-08-10T11:00:00Z',
    lastContactedAt: '2026-08-30T16:00:00Z',
  },
  {
    id: 'lead_6',
    firstName: 'Priya',
    lastName: 'Sharma',
    fullName: 'Priya Sharma',
    email: 'priya.sharma@synthetix.ai',
    phone: '+1 (650) 338-7120',
    title: 'VP of AI Research & Partnerships',
    seniority: 'VP / Head of',
    department: 'AI & Data Science',
    company: 'Synthetix AI Labs',
    companyDomain: 'synthetix.ai',
    companyLogo: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=100&auto=format&fit=crop&q=60',
    companySize: '11-50',
    annualRevenue: '$5M - $10M',
    industry: 'Artificial Intelligence',
    subIndustry: 'Foundation Models & LLM Tooling',
    location: 'Palo Alto, CA, USA',
    city: 'Palo Alto',
    state: 'CA',
    country: 'United States',
    linkedin: 'https://linkedin.com/in/priya-sharma-ai',
    twitter: '@priya_deepai',
    website: 'https://synthetix.ai',
    leadScore: 91,
    emailStatus: 'verified',
    leadStatus: 'closed_won',
    source: 'web_scraper',
    tags: ['AI Native', 'Fast Mover', 'Customer'],
    notes: 'Signed standard annual enterprise tier. Kickoff scheduled for next Monday.',
    techStack: ['PyTorch', 'NVIDIA Triton', 'Next.js', 'Pinecone', 'Weights & Biases'],
    intentScore: 'High',
    revealed: true,
    createdAt: '2026-08-05T13:20:00Z',
    lastContactedAt: '2026-08-25T15:00:00Z',
  },
  {
    id: 'lead_7',
    firstName: 'Julian',
    lastName: 'Dubois',
    fullName: 'Julian Dubois',
    email: 'j.dubois@aerologistix.fr',
    phone: '+33 1 42 68 55 00',
    title: 'Supply Chain Operations Director',
    seniority: 'Director',
    department: 'Logistics & Supply Chain',
    company: 'AeroLogistix Europe',
    companyDomain: 'aerologistix.fr',
    companyLogo: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=100&auto=format&fit=crop&q=60',
    companySize: '501-1,000',
    annualRevenue: '$90M - $180M',
    industry: 'Logistics & Supply Chain',
    subIndustry: 'Freight & Fleet Management',
    location: 'Paris, France',
    city: 'Paris',
    country: 'France',
    linkedin: 'https://linkedin.com/in/julian-dubois-logistics',
    website: 'https://aerologistix.fr',
    leadScore: 74,
    emailStatus: 'verified',
    leadStatus: 'contacted',
    source: 'csv_import',
    tags: ['European Hub', 'Cold Chain', 'Fleet IoT'],
    notes: 'Engaged with automated email sequence step 2. Replied inquiring about API latency.',
    techStack: ['SAP S/4HANA', 'Oracle Cloud', 'Geotab', 'Power BI'],
    intentScore: 'Medium',
    revealed: true,
    createdAt: '2026-08-19T07:40:00Z',
    lastContactedAt: '2026-08-27T09:30:00Z',
  },
  {
    id: 'lead_8',
    firstName: 'Claire',
    lastName: 'O\'Connor',
    fullName: 'Claire O\'Connor',
    email: 'claire@eduvance.org',
    phone: '+1 (512) 904-3321',
    title: 'Chief Academic Officer & Co-Founder',
    seniority: 'Founder / C-Level',
    department: 'Executive Leadership',
    company: 'EduVance Interactive',
    companyDomain: 'eduvance.org',
    companyLogo: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=100&auto=format&fit=crop&q=60',
    companySize: '51-200',
    annualRevenue: '$8M - $15M',
    industry: 'EdTech & Learning',
    subIndustry: 'K-12 & Higher Ed SaaS',
    location: 'Austin, TX, USA',
    city: 'Austin',
    state: 'TX',
    country: 'United States',
    linkedin: 'https://linkedin.com/in/claire-oconnor-ed',
    twitter: '@claire_eduvance',
    website: 'https://eduvance.org',
    leadScore: 68,
    emailStatus: 'catch-all',
    leadStatus: 'new',
    source: 'ai_discovery',
    tags: ['EdTech Leader', 'Series A', 'Austin'],
    notes: 'Rapidly expanding to university campus licenses.',
    techStack: ['Canvas LMS', 'React', 'PostgreSQL', 'AWS Lambda', 'Mixpanel'],
    intentScore: 'Low',
    revealed: false,
    createdAt: '2026-08-26T16:00:00Z',
  },
  {
    id: 'lead_9',
    firstName: 'Mateo',
    lastName: 'Silva',
    fullName: 'Mateo Silva',
    email: 'mateo.silva@solargenx.energy',
    phone: '+1 (303) 881-4478',
    title: 'Director of Asset Optimization',
    seniority: 'Director',
    department: 'Renewable Engineering',
    company: 'SolarGenX Renewables',
    companyDomain: 'solargenx.energy',
    companyLogo: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?w=100&auto=format&fit=crop&q=60',
    companySize: '201-500',
    annualRevenue: '$40M - $75M',
    industry: 'CleanTech & Energy',
    subIndustry: 'Solar & Grid Battery Storage',
    location: 'Denver, CO, USA',
    city: 'Denver',
    state: 'CO',
    country: 'United States',
    linkedin: 'https://linkedin.com/in/mateo-silva-solar',
    website: 'https://solargenx.energy',
    leadScore: 85,
    emailStatus: 'verified',
    leadStatus: 'qualified',
    source: 'web_scraper',
    tags: ['Clean Energy', 'Grid IoT', 'B2B'],
    notes: 'Interested in real-time sensor analytics dashboard integration.',
    techStack: ['SCADA', 'TimescaleDB', 'Python', 'Grafana', 'Google Cloud Platform'],
    intentScore: 'High',
    revealed: false,
    createdAt: '2026-08-24T12:00:00Z',
  },
  {
    id: 'lead_10',
    firstName: 'Rachel',
    lastName: 'Stern',
    fullName: 'Rachel Stern',
    email: 'rachel@apexproptech.com',
    phone: '+1 (305) 602-9844',
    title: 'Head of Commercial Real Estate Tech',
    seniority: 'VP / Head of',
    department: 'Real Estate Development',
    company: 'Apex PropTech & Assets',
    companyDomain: 'apexproptech.com',
    companyLogo: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=100&auto=format&fit=crop&q=60',
    companySize: '51-200',
    annualRevenue: '$18M - $35M',
    industry: 'Real Estate & PropTech',
    subIndustry: 'Commercial Asset Management',
    location: 'Miami, FL, USA',
    city: 'Miami',
    state: 'FL',
    country: 'United States',
    linkedin: 'https://linkedin.com/in/rachel-stern-proptech',
    website: 'https://apexproptech.com',
    leadScore: 71,
    emailStatus: 'verified',
    leadStatus: 'contacted',
    source: 'domain_extractor',
    tags: ['PropTech', 'Miami Metro', 'Tenant Portal'],
    notes: 'Outreach email sent yesterday with customized Miami market benchmarking report.',
    techStack: ['Yardi', 'HubSpot', 'WordPress', 'Google Analytics 4'],
    intentScore: 'Medium',
    revealed: true,
    createdAt: '2026-08-25T11:20:00Z',
    lastContactedAt: '2026-08-30T10:15:00Z',
  },
  {
    id: 'lead_11',
    firstName: 'Takahiro',
    lastName: 'Tanaka',
    fullName: 'Takahiro Tanaka',
    email: 't-tanaka@robotix-global.jp',
    phone: '+81 3 5555 0192',
    title: 'Chief Robotics Architect',
    seniority: 'Founder / C-Level',
    department: 'R&D Hardware & Embedded Systems',
    company: 'RoboTix Dynamics',
    companyDomain: 'robotix-global.jp',
    companyLogo: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=100&auto=format&fit=crop&q=60',
    companySize: '1,001-5,000',
    annualRevenue: '$200M - $500M',
    industry: 'Manufacturing & Robotics',
    subIndustry: 'Industrial Automation',
    location: 'Tokyo, Japan',
    city: 'Tokyo',
    country: 'Japan',
    linkedin: 'https://linkedin.com/in/takahiro-tanaka-robotics',
    website: 'https://robotix-global.jp',
    leadScore: 92,
    emailStatus: 'verified',
    leadStatus: 'meeting_scheduled',
    source: 'ai_discovery',
    tags: ['APAC Expansion', 'Global Enterprise', 'High Value'],
    notes: 'Technical discovery session booked for next Tuesday morning Tokyo time.',
    techStack: ['ROS2', 'C++', 'CUDA', 'AWS IoT Greengrass', 'SolidWorks'],
    intentScore: 'High',
    revealed: true,
    createdAt: '2026-08-21T04:10:00Z',
    lastContactedAt: '2026-08-29T23:30:00Z',
  },
  {
    id: 'lead_12',
    firstName: 'Jessica',
    lastName: 'Kowalski',
    fullName: 'Jessica Kowalski',
    email: 'j.kowalski@pulsehealth.co',
    phone: '+1 (206) 492-3301',
    title: 'VP of Patient Engagement',
    seniority: 'VP / Head of',
    department: 'Healthcare Operations',
    company: 'PulseHealth Systems',
    companyDomain: 'pulsehealth.co',
    companyLogo: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=100&auto=format&fit=crop&q=60',
    companySize: '201-500',
    annualRevenue: '$30M - $60M',
    industry: 'Healthcare & Biotech',
    subIndustry: 'RPM & Tele-monitoring',
    location: 'Seattle, WA, USA',
    city: 'Seattle',
    state: 'WA',
    country: 'United States',
    linkedin: 'https://linkedin.com/in/jessica-kowalski-pulse',
    website: 'https://pulsehealth.co',
    leadScore: 86,
    emailStatus: 'verified',
    leadStatus: 'qualified',
    source: 'web_scraper',
    tags: ['RPM', 'Seattle Tech', 'HIPAA'],
    notes: 'Reviewed pricing tier. Ready for procurement approval next month.',
    techStack: ['Cerner', 'Twilio', 'React Native', 'AWS', 'Salesforce Health Cloud'],
    intentScore: 'High',
    revealed: false,
    createdAt: '2026-08-17T15:20:00Z',
  }
];

export const INITIAL_COMPANIES: Company[] = [
  {
    id: 'comp_1',
    name: 'CloudScale Systems',
    domain: 'cloudscale.io',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=60',
    industry: 'Software & SaaS',
    subIndustry: 'Cloud Infrastructure & DevOps',
    employeeCount: '201-500',
    revenueRange: '$25M - $50M',
    foundedYear: 2019,
    headquarters: 'San Francisco, CA, USA',
    phone: '+1 (415) 892-4000',
    techStack: ['Kubernetes', 'AWS', 'Terraform', 'Datadog', 'PostgreSQL', 'Golang', 'Next.js'],
    linkedinUrl: 'https://linkedin.com/company/cloudscale-systems',
    website: 'https://cloudscale.io',
    description: 'Enterprise multi-cloud orchestration and developer tooling for hyper-scale engineering teams.',
    intentScore: 'High',
    leadsCount: 1,
  },
  {
    id: 'comp_2',
    name: 'FinFlow Payments',
    domain: 'finflow.pay',
    logo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=100&auto=format&fit=crop&q=60',
    industry: 'FinTech',
    subIndustry: 'Cross-border Payments & Banking',
    employeeCount: '51-200',
    revenueRange: '$15M - $30M',
    foundedYear: 2021,
    headquarters: 'New York, NY, USA',
    phone: '+1 (212) 441-9000',
    techStack: ['Stripe', 'Node.js', 'React', 'Snowflake', 'Segment', 'Redis', 'Tailwind'],
    linkedinUrl: 'https://linkedin.com/company/finflow-pay',
    website: 'https://finflow.pay',
    description: 'Next-gen global payout infrastructure and compliance ledger for marketplaces.',
    intentScore: 'High',
    leadsCount: 1,
  },
  {
    id: 'comp_3',
    name: 'CyberShield Global',
    domain: 'cybershield.security',
    logo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=100&auto=format&fit=crop&q=60',
    industry: 'Cybersecurity',
    subIndustry: 'Threat Intelligence & SOC',
    employeeCount: '1,001-5,000',
    revenueRange: '$150M - $300M',
    foundedYear: 2015,
    headquarters: 'London, United Kingdom',
    phone: '+44 20 7946 0900',
    techStack: ['Okta', 'CrowdStrike', 'Splunk', 'Azure', 'Palo Alto Networks', 'Docker', 'Kubernetes'],
    linkedinUrl: 'https://linkedin.com/company/cybershield-global',
    website: 'https://cybershield.security',
    description: 'Autonomous threat detection, proactive penetration simulation, and Managed SOC services for Fortune 500s.',
    intentScore: 'High',
    leadsCount: 1,
  },
  {
    id: 'comp_4',
    name: 'Synthetix AI Labs',
    domain: 'synthetix.ai',
    logo: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=100&auto=format&fit=crop&q=60',
    industry: 'Artificial Intelligence',
    subIndustry: 'Foundation Models & LLM Tooling',
    employeeCount: '11-50',
    revenueRange: '$5M - $10M',
    foundedYear: 2023,
    headquarters: 'Palo Alto, CA, USA',
    phone: '+1 (650) 338-7000',
    techStack: ['PyTorch', 'NVIDIA Triton', 'Next.js', 'Pinecone', 'Weights & Biases', 'FastAPI'],
    linkedinUrl: 'https://linkedin.com/company/synthetix-ai',
    website: 'https://synthetix.ai',
    description: 'Synthetic data generation and fine-tuning pipelines for enterprise generative AI deployments.',
    intentScore: 'High',
    leadsCount: 1,
  },
  {
    id: 'comp_5',
    name: 'BioHealth Era',
    domain: 'biohealthera.com',
    logo: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=100&auto=format&fit=crop&q=60',
    industry: 'Healthcare & Biotech',
    subIndustry: 'Digital Health & Telemedicine',
    employeeCount: '501-1,000',
    revenueRange: '$80M - $120M',
    foundedYear: 2017,
    headquarters: 'Boston, MA, USA',
    phone: '+1 (617) 552-8800',
    techStack: ['Epic EHR', 'AWS HealthLake', 'FastAPI', 'Postgres', 'React Native'],
    linkedinUrl: 'https://linkedin.com/company/biohealth-era',
    website: 'https://biohealthera.com',
    description: 'Transforming clinical workflows and patient triage with automated data synthesis.',
    intentScore: 'Medium',
    leadsCount: 1,
  }
];

export const INITIAL_LISTS: LeadList[] = [
  {
    id: 'list_1',
    name: 'Tier-1 C-Suite Target Accounts',
    description: 'CTOs and CISOs from high-growth tech companies with verified emails',
    color: '#06b6d4',
    leadIds: ['lead_1', 'lead_5', 'lead_11'],
    createdAt: '2026-08-15T12:00:00Z',
  },
  {
    id: 'list_2',
    name: 'FinTech & Payments Decision Makers',
    description: 'VPs and Heads of Product in cross-border finance',
    color: '#10b981',
    leadIds: ['lead_2'],
    createdAt: '2026-08-18T14:00:00Z',
  },
  {
    id: 'list_3',
    name: 'HealthTech & Bio Informatics',
    description: 'Clinical directors and RPM operations leads',
    color: '#8b5cf6',
    leadIds: ['lead_3', 'lead_12'],
    createdAt: '2026-08-20T16:00:00Z',
  }
];

export const INITIAL_CAMPAIGNS: CampaignSequence[] = [
  {
    id: 'camp_1',
    name: 'High-Intent CTO Scalability Sequence',
    status: 'active',
    targetIndustry: 'Software & SaaS',
    enrolledLeadIds: ['lead_1', 'lead_5'],
    stats: {
      sent: 48,
      opened: 36,
      clicked: 19,
      replied: 12,
      bounced: 1,
    },
    steps: [
      {
        stepNumber: 1,
        delayDays: 0,
        subject: 'Solving data pipeline friction at {{company}}',
        bodyTemplate: 'Hi {{firstName}},\n\nI noticed you\'re leading technology at {{company}}. Most {{title}}s in {{industry}} we talk to struggle with scaling their lead intelligence and API latency.\n\nWe built an autonomous scraper and CRM sync that extracts 100% verified prospects directly into your pipeline.\n\nWorth a 7-minute intro this Thursday?\n\nBest,\nAlex',
        isAiPersonalized: true,
      },
      {
        stepNumber: 2,
        delayDays: 3,
        subject: 'Quick idea for {{company}}\'s team',
        bodyTemplate: 'Hey {{firstName}},\n\nJust wanted to float this back to your inbox. Attached is a quick benchmark report showing how peer companies in {{industry}} automated their prospect verification.\n\nLet me know if you have 5 minutes to connect.\n\nCheers,\nAlex',
        isAiPersonalized: true,
      }
    ],
    createdAt: '2026-08-16T10:00:00Z',
  },
  {
    id: 'camp_2',
    name: 'FinTech Growth & Payouts Outreach',
    status: 'active',
    targetIndustry: 'FinTech',
    enrolledLeadIds: ['lead_2'],
    stats: {
      sent: 32,
      opened: 24,
      clicked: 14,
      replied: 8,
      bounced: 0,
    },
    steps: [
      {
        stepNumber: 1,
        delayDays: 0,
        subject: 'Streamlining customer onboarding at {{company}}',
        bodyTemplate: 'Hi {{firstName}},\n\nSaw your recent growth at {{company}}. With your expansion in {{location}}, how are you currently managing lead enrichment across your outbound team?\n\nWould love to share how we helped similar FinTech leaders reduce bounce rates to under 1%.\n\nBest,\nAlex',
        isAiPersonalized: true,
      }
    ],
    createdAt: '2026-08-19T11:30:00Z',
  }
];
